import { spawn } from 'node:child_process';
import { existsSync, mkdirSync, mkdtempSync, readFileSync, rmSync, writeFileSync } from 'node:fs';
import { tmpdir } from 'node:os';
import path from 'node:path';
import { pathToFileURL } from 'node:url';

import { parse } from 'jsonc-parser';
import { afterEach, describe, expect, it } from 'vitest';

import { resolveRepository } from '../src/git.js';
import { type SetupCommandResult, setup } from '../src/setup.js';
import { repository, type TestRepository } from './helpers.js';

const repositories: TestRepository[] = [];
const homes: string[] = [];
afterEach(() => {
  for (const entry of repositories.splice(0)) entry.cleanup();
  for (const home of homes.splice(0)) rmSync(home, { recursive: true, force: true });
});

function fixture(): { root: string; home: string; commands: string[][] } {
  const created = repository();
  repositories.push(created);
  const home = mkdtempSync(path.join(tmpdir(), 'clankchat-home-'));
  homes.push(home);
  return { root: created.root, home, commands: [] };
}

function commandResult(command: string, args: string[]): SetupCommandResult {
  if (command === 'claude' && args.join(' ') === 'mcp get clankchat') {
    return { status: 1, stdout: '', stderr: 'not found' };
  }
  if (command === 'claude' && args.includes('--json')) {
    return { status: 0, stdout: '[]', stderr: '' };
  }
  return { status: 0, stdout: '', stderr: '' };
}

describe('setup', () => {
  it('configures both harnesses and removes stale integration data surgically', () => {
    const { root, home, commands } = fixture();
    mkdirSync(path.join(root, '.opencode', 'plugins'), { recursive: true });
    mkdirSync(path.join(root, '.sametree'), { recursive: true });
    writeFileSync(path.join(root, '.sametree', 'config.json'), '{}\n');
    writeFileSync(
      path.join(root, '.opencode', 'opencode.jsonc'),
      `{
  // keep this comment
  "mcp": {
    "other": { "type": "remote", "url": "https://example.com" },
    "sametree": { "type": "local", "command": ["sametree-mcp"] }
  },
  "instructions": ["README.md", ".sametree/coordination.md"]
}
`,
    );
    writeFileSync(
      path.join(root, '.opencode', 'tui.json'),
      '{ "plugin": ["./other.ts", "./sametree-tui.ts"] }\n',
    );
    writeFileSync(path.join(root, '.opencode', 'sametree-tui.ts'), '// Generated by SameTree.\n');
    writeFileSync(
      path.join(root, '.opencode', 'plugins', 'sametree-plan-publisher.ts'),
      '// Generated by SameTree.\n',
    );
    writeFileSync(
      path.join(root, 'CLAUDE.local.md'),
      'Keep me.\n\n<!-- sametree:coordination -->\nold\n<!-- /sametree:coordination -->\n',
    );

    const result = setup({
      cwd: root,
      homeDirectory: home,
      commandRunner: (command, args) => {
        commands.push([command, ...args]);
        return commandResult(command, args);
      },
    });

    expect(result.configured).toEqual(['claude-code', 'opencode']);
    expect(result.removedStaleConfiguration).toBe(true);
    expect(result.databasePath).toContain('/clankchat/state.sqlite3');
    expect(existsSync(path.join(root, '.sametree'))).toBe(false);
    const configText = readFileSync(path.join(root, '.opencode', 'opencode.jsonc'), 'utf8');
    const config = parse(configText) as Record<string, unknown>;
    expect(configText).toContain('// keep this comment');
    expect(config).toMatchObject({
      mcp: { other: { type: 'remote' }, clankchat: { command: ['clankchat-mcp'] } },
    });
    expect(JSON.stringify(config)).not.toContain('sametree');
    expect(readFileSync(path.join(root, '.opencode', 'tui.json'), 'utf8')).toContain(
      './clankchat-tui.ts',
    );
    expect(readFileSync(path.join(root, 'CLAUDE.local.md'), 'utf8')).toContain('Keep me.');
    expect(readFileSync(path.join(root, 'CLAUDE.local.md'), 'utf8')).toContain('## clankchat');
    expect(existsSync(path.join(root, '.opencode', 'sametree-tui.ts'))).toBe(false);
    expect(existsSync(path.join(root, '.opencode', 'plugins', 'sametree-plan-publisher.ts'))).toBe(
      false,
    );
    expect(commands.some((entry) => entry.includes('clankchat@clankchat'))).toBe(true);
  });

  it('is idempotent on repeated setup', () => {
    const { root, home } = fixture();
    const options = { cwd: root, homeDirectory: home, commandRunner: commandResult };
    setup(options);
    const files = [
      'CLAUDE.local.md',
      '.opencode/opencode.json',
      '.opencode/clankchat.md',
      '.opencode/clankchat-tui.ts',
      '.opencode/plugins/clankchat.ts',
      '.opencode/tui.json',
    ];
    const before = files.map((file) => readFileSync(path.join(root, file), 'utf8'));
    const second = setup(options);
    expect(second.removedStaleConfiguration).toBe(false);
    expect(files.map((file) => readFileSync(path.join(root, file), 'utf8'))).toEqual(before);
  });

  it('refuses concurrent setup for the same clone', () => {
    const { root, home } = fixture();
    const stateDirectory = path.join(resolveRepository(root).commonGitDirectory, 'clankchat');
    mkdirSync(stateDirectory, { recursive: true });
    writeFileSync(
      path.join(stateDirectory, 'setup.lock'),
      `${JSON.stringify({ processId: process.pid, startedAt: Date.now() })}\n`,
    );
    expect(() => setup({ cwd: root, homeDirectory: home, commandRunner: commandResult })).toThrow(
      /already running/u,
    );
  });

  it('preserves unrelated entries and tuple-valued OpenCode plugins', () => {
    const { root, home } = fixture();
    mkdirSync(path.join(root, '.opencode'), { recursive: true });
    writeFileSync(
      path.join(root, '.opencode', 'opencode.json'),
      '{ "instructions": ["docs/sametree-notes.md"] }\n',
    );
    writeFileSync(
      path.join(root, '.opencode', 'tui.json'),
      '{ "plugin": [["./other.ts", { "mode": "safe" }]] }\n',
    );

    setup({ cwd: root, homeDirectory: home, opencode: true });

    const config = parse(readFileSync(path.join(root, '.opencode', 'opencode.json'), 'utf8')) as {
      instructions: unknown[];
    };
    const tui = parse(readFileSync(path.join(root, '.opencode', 'tui.json'), 'utf8')) as {
      plugin: unknown[];
    };
    expect(config.instructions).toContain('docs/sametree-notes.md');
    expect(tui.plugin).toContainEqual(['./other.ts', { mode: 'safe' }]);
  });

  it('refuses conflicting registrations and unowned generated paths', () => {
    const { root, home } = fixture();
    mkdirSync(path.join(root, '.opencode'), { recursive: true });
    writeFileSync(
      path.join(root, '.opencode', 'opencode.json'),
      '{ "mcp": { "clankchat": { "type": "remote", "url": "https://example.com" } } }\n',
    );
    expect(() => setup({ cwd: root, homeDirectory: home, opencode: true })).toThrow(/conflicting/u);

    writeFileSync(path.join(root, '.opencode', 'opencode.json'), '{}\n');
    writeFileSync(path.join(root, '.opencode', 'clankchat.md'), '# Mine\n');
    expect(() => setup({ cwd: root, homeDirectory: home, opencode: true })).toThrow(/unowned/u);
  });

  it('reports Claude Code command failures', () => {
    const { root, home } = fixture();
    expect(() =>
      setup({
        cwd: root,
        homeDirectory: home,
        claude: true,
        commandRunner: (command, args) => {
          if (args.includes('--json')) return commandResult(command, args);
          if (args.join(' ') === 'mcp get clankchat') {
            return { status: 1, stdout: '', stderr: 'not found' };
          }
          if (args.includes('add')) return { status: 1, stdout: '', stderr: 'rejected' };
          return commandResult(command, args);
        },
      }),
    ).toThrow(/rejected/u);
    expect(existsSync(path.join(root, 'CLAUDE.local.md'))).toBe(false);
  });

  it('preflights all OpenCode files before writing', () => {
    const { root, home } = fixture();
    mkdirSync(path.join(root, '.opencode'), { recursive: true });
    writeFileSync(path.join(root, '.opencode', 'tui.json'), '{}\n');
    writeFileSync(path.join(root, '.opencode', 'tui.jsonc'), '{}\n');

    expect(() => setup({ cwd: root, homeDirectory: home, opencode: true })).toThrow(/Both/u);
    expect(existsSync(path.join(root, '.opencode', 'opencode.json'))).toBe(false);
    expect(existsSync(path.join(root, '.opencode', 'clankchat.md'))).toBe(false);
    expect(existsSync(path.join(root, '.opencode', 'clankchat-tui.ts'))).toBe(false);
  });

  it('never removes a setup lock automatically', () => {
    const { root, home } = fixture();
    const stateDirectory = path.join(resolveRepository(root).commonGitDirectory, 'clankchat');
    mkdirSync(stateDirectory, { recursive: true });
    writeFileSync(
      path.join(stateDirectory, 'setup.lock'),
      `${JSON.stringify({ processId: 2_147_483_647, startedAt: 0 })}\n`,
    );

    expect(() => setup({ cwd: root, homeDirectory: home, opencode: true })).toThrow(/previous/u);
    expect(existsSync(path.join(stateDirectory, 'setup.lock'))).toBe(true);
  });

  it('rejects every contender when a stale lock exists', async () => {
    const { root, home } = fixture();
    const stateDirectory = path.join(resolveRepository(root).commonGitDirectory, 'clankchat');
    mkdirSync(stateDirectory, { recursive: true });
    writeFileSync(
      path.join(stateDirectory, 'setup.lock'),
      `${JSON.stringify({ processId: 2_147_483_647, startedAt: 0 })}\n`,
    );
    const setupModule = pathToFileURL(path.resolve('dist/setup.js')).href;
    const source = `
      import { setup } from ${JSON.stringify(setupModule)};
      const wait = () => Atomics.wait(new Int32Array(new SharedArrayBuffer(4)), 0, 0, 300);
      const commandRunner = (_command, args) => {
        if (args.join(" ") === "mcp get clankchat") {
          wait();
          return { status: 1, stdout: "", stderr: "not found" };
        }
        if (args.includes("--json")) return { status: 0, stdout: "[]", stderr: "" };
        return { status: 0, stdout: "", stderr: "" };
      };
      try {
        setup({ cwd: ${JSON.stringify(root)}, homeDirectory: ${JSON.stringify(home)}, claude: true, commandRunner });
      } catch (error) {
        process.stderr.write(error instanceof Error ? error.message : String(error));
        process.exitCode = 1;
      }
    `;
    const run = () =>
      new Promise<{ code: number | null; stderr: string }>((resolve) => {
        const child = spawn(process.execPath, ['--input-type=module', '--eval', source], {
          stdio: ['ignore', 'ignore', 'pipe'],
        });
        let stderr = '';
        child.stderr.setEncoding('utf8');
        child.stderr.on('data', (chunk: string) => {
          stderr += chunk;
        });
        child.once('exit', (code) => resolve({ code, stderr }));
      });

    const results = await Promise.all([run(), run()]);
    expect(results.map((result) => result.code)).toEqual([1, 1]);
    expect(results.map((result) => result.stderr)).toEqual([
      expect.stringMatching(/previous setup/u),
      expect.stringMatching(/previous setup/u),
    ]);
  });

  it('refuses malformed instruction ownership markers', () => {
    const { root, home } = fixture();
    writeFileSync(path.join(root, 'CLAUDE.local.md'), 'Keep me.\n<!-- clankchat:start -->\n');
    expect(() =>
      setup({ cwd: root, homeDirectory: home, claude: true, commandRunner: commandResult }),
    ).toThrow(/marker/u);
    expect(readFileSync(path.join(root, 'CLAUDE.local.md'), 'utf8')).toBe(
      'Keep me.\n<!-- clankchat:start -->\n',
    );
  });
});
